daysUntilStale: 30
daysUntilClose: 7
onlyLabels: []
exemptLabels:
  - pinned
  - security

exemptProjects: false
exemptMilestones: true
exemptAssignees: false
staleLabel: stale

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

limitPerRun: 30
