checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
builds:
  - id: watcher
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
brews:
  - name: polaris
    github:
      owner: FairwindsOps
      name: homebrew-tap
    folder: Formula
    description: Open Source Best Practices for Kubernetes
    test: |
      system "#{bin}/polaris version"
