checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: polaris
    github:
      owner: FairwindsOps
      name: homebrew-tap
    folder: Formula
    description: Open Source Best Practices for Kubernetes
    test: |
      system "#{bin}/polaris version"
