checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
builds:
  - id: polaris
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - id: polaris
    builds: ["polaris"]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
brews:
  - name: polaris
    github:
      owner: FairwindsOps
      name: homebrew-tap
    folder: Formula
    description: Open Source Best Practices for Kubernetes
    test: |
      system "#{bin}/polaris version"
