{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "fairwinds.fullname" . }}
  labels:
    {{- include "fairwinds.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ''
    - 'apps'
    - 'admissionregistration.k8s.io'
    resources:
      - '*'
    verbs:
      - '*'
{{- end -}}
