apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fairwinds.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fairwinds.name" . }}
    helm.sh/chart: {{ include "fairwinds.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: {{- toYaml .Values.config | indent 2 -}}
