apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fairwinds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fairwinds.labels" . | nindent 4 }}
data:
  config.yaml: {{- toYaml .Values.config | indent 2 -}}
