{{- if .Values.webhook.enable -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    checksum/config: '{{ include (print $.Template.BasePath "/fairwinds.configmap.yaml") . | sha256sum }}'
  name: {{ include "fairwinds.fullname" . }}-webhook
  labels:
    app.kubernetes.io/name: {{ include "fairwinds.name" . }}
    helm.sh/chart: {{ include "fairwinds.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: webhook
spec:
  replicas: {{ .Values.webhook.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fairwinds.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fairwinds.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: webhook
    spec:
      volumes:
      - configMap:
          name:  {{ include "fairwinds.name" . }}
        name:  {{ include "fairwinds.name" . }}
      - name: certs
        secret:
          secretName:  {{ include "fairwinds.name" . }}
      containers:
      - command:
        - fairwinds
        - --webhook
        image: '{{.Values.webhook.image.repository}}:{{.Values.webhook.image.tag}}'
        imagePullPolicy: '{{.Values.webhook.image.pullPolicy}}'
        name: webhook
        ports:
        - containerPort: 9876
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - ps -ef | grep fairwinds
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /tmp/cert/
          name: certs
        - mountPath: /opt/app/config.yml
          name:  {{ include "fairwinds.name" . }}
          readOnly: true
          subPath: config.yml
      serviceAccountName:  {{ include "fairwinds.name" . }}
{{- end -}}
