apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test
  labels:
    k8s-app: test
spec:
  selector:
    matchLabels:
      name: test
  template:
    metadata:
      labels:
        name: test
    spec:
      containers:
      - name: test
        image: busybox
        command: ["whoami"]
        resources: {}
