successMessage: CPU limits are set
failureMessage: CPU limits should be set
category: Efficiency
target: Container
containers:
  exclude:
  - initContainer
schema:
  '$schema': http://json-schema.org/draft-07/schema
  type: object
  required:
  - resources
  properties:
    resources:
      type: object
      required:
      - limits
      properties:
        limits:
          type: object
          required:
          - cpu
          properties:
            cpu:
              type: string
              not:
                const: ''
mutations:
  - op: add
    path: /resources/limits/cpu
    value: 100m
    comment: "TODO: Set this to the maximum amount of CPU you want your workload to use"
