successMessage: CPU requests are set
failureMessage: CPU requests should be set
category: Efficiency
target: Container
containers:
  exclude:
  - initContainer
schema:
  '$schema': http://json-schema.org/draft-07/schema
  type: object
  required:
  - resources
  properties:
    resources:
      type: object
      required:
      - requests
      properties:
        requests:
          type: object
          required:
          - cpu
          properties:
            cpu:
              type: string
              not:
                const: ''
