successMessage: Host network is not configured
failureMessage: Host network should not be configured
category: Security
target: PodSpec
schema:
  "$schema": "http://json-schema.org/draft/2019-09/schema"
  type: object
  properties:
    hostNetwork:
      not:
        const: true
mutations:
  - op: remove
    path: /hostNetwork