successMessage: Host port is not configured
failureMessage: Host port should not be configured
category: Security
target: Container
schema:
  '$schema': http://json-schema.org/draft-07/schema
  type: object
  required:
  properties:
    ports:
      oneOf:
        - type: "null"
        - type: "array"
          items:
            not:
              properties:
                hostPort:
                  not:
                    enum: [0, null]
              required: ["hostPort"]
mutations:
  - op: remove
    path: /ports/*/hostPort
