successMessage: Host IPC is not configured
failureMessage: Host IPC should not be configured
category: Security
target: PodSpec
schema:
  '$schema': https://json-schema.org/draft/2019-09/schema
  type: object
  properties:
    hostIPC:
      not:
        const: true
mutations:
  - op: remove
    path: /hostIPC