successMessage: HPA has a valid min replica configuration
failureMessage: HPA minReplicas should be 2 or more
category: Reliability
target: autoscaling/HorizontalPodAutoscaler
schema:
  "$schema": http://json-schema.org/draft/2019-09/schema#
  type: object
  properties:
    spec:
      type: object
      properties:
        minReplicas:
          type: integer
          minimum: 2
