successMessage: Privilege escalation not allowed
failureMessage: Privilege escalation should not be allowed
category: Security
target: Container
schemaTarget: PodSpec
schema:
  '$schema': http://json-schema.org/draft/2019-09/schema
  $defs:
    goodSecurityContext:
      type: object
      anyOf:
      - required:
        - allowPrivilegeEscalation
        properties:
          allowPrivilegeEscalation:
            const: false
    notBadSecurityContext:
      type: object
      properties:
        allowPrivilegeEscalation:
          const: false
  type: object
  anyOf:
  - required:
    - securityContext
    properties:
      securityContext:
        $ref: "#/$defs/goodSecurityContext"
      containers:
        type: array
        items:
          properties:
            securityContext:
              $ref: "#/$defs/notBadSecurityContext"
  - properties:
      containers:
        type: array
        items:
          required:
          - securityContext
          properties:
            securityContext:
              $ref: "#/$defs/goodSecurityContext"

mutations:
  - op: add
    path: /securityContext/allowPrivilegeEscalation
    value: false
