successMessage: Image pull policy is "Always"
failureMessage: Image pull policy should be "Always"
category: Reliability
target: Container
schema:
  '$schema': http://json-schema.org/draft-07/schema
  required:
  - imagePullPolicy
  properties:
    containers:
      type: array
      items:
        type: object
        properties:
          imagePullPolicy:
            const: Always
mutations:
  - op: add
    path: /imagePullPolicy
    value: Always