successMessage: Is not allowed to run as root
failureMessage: Should not be allowed to run as root
category: Security
target: Container
schemaTarget: PodSpec
jsonSchema: |
  {
    "$schema": "http://json-schema.org/draft-07/schema",
    "definitions": {
      "goodSecurityContext": {
        "type": "object",
        "anyOf": [
          {
            "required": ["runAsUser"],
            "properties": {
              "runAsUser": {
                "minimum": 1
              }
            }
          },
          {
            "required": ["runAsNonRoot"],
            "properties": {
              "runAsNonRoot": {
                "const": true
              }
            }
          }
        ]
      },
      "notBadSecurityContext": {
        "type": "object",
        "properties": {
          "runAsUser": {
            "minimum": 1
          },
          "runAsNonRoot": {
            "const": true
          }
        }
      }
    },
    "type": "object",
    "anyOf": [
      {
        "required": ["securityContext"],
        "properties": {
          "securityContext": {
            "$ref": "#/definitions/goodSecurityContext"
          },
          "containers": {
            "type": "array",
            "items": {
              "properties": {
                "securityContext": {
                  "$ref": "#/definitions/notBadSecurityContext"
                }
              }
            }
          }
        }
      },
      {
        "properties": {
          "containers": {
            "type": "array",
            "items": {
              "required": ["securityContext"],
              "properties": {
                "securityContext": {
                  "$ref": "#/definitions/goodSecurityContext"
                }
              }
            }
          }
        }
      }
    ]
  }
mutations:
  - op: add
    path: /securityContext/runAsNonRoot
    value: true
