successMessage: Image tag is specified
failureMessage: Image tag should be specified
category: Reliability
target: Container
schema:
  '$schema': https://json-schema.org/draft/2019-09/schema
  required:
  - image
  allOf:
  - properties:
      image:
        pattern: ^.+:.+$
  - properties:
      image:
        not:
          pattern: ^.+:latest$
