apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: two
spec:
  restartPolicy: Never
  containers:
  - name: hello
    image: "ubuntu:14.04"
    command: ["/bin/echo", "hello", "world"]
