name: Test setup-polaris
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-int:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup polaris
        uses: ./
        with:
          version: 3.0.3
      - name: Use command
        run: polaris version
  build-ext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup polaris
        uses: fairwindsops/polaris@master
        with:
          version: 3.0.3
      - name: Use command
        run: polaris version