name: Triage issues
on:
  issues:
    types:
      - reopened
      - opened
  pull_request:
jobs:
  notify:
    if: github.actor!= 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        if: steps.filter.outputs.is_pull_request == 'true'
        env:
          TITLE: "{{ github.event.pull_request.title }}"
          LINK: "github.com/${{ github.event.repository.name }}/pulls/${{ github.event.pull_request.id }}"
        run: |
          curl -X POST "${{ secrets.SLACK_INCOMING_WEBHOOK }}" -H "Content-type: application/json" -d '{
            "text": "New Pull Request",
            "blocks": [
            	{
            		"type": "section",
            		"text": {
            			"type": "mrkdwn",
            			"text": "New Pull Request: ${TITLE}"
            		}
            	},
            	{
            		"type": "section",
            		"text": {
            			"type": "mrkdwn",
            			"text": "$LINK"
            		},
            	},
            ]
          }'
