name: Triage issues
on:
  schedule:
  - cron: '0 16 * * Mon' # noon ET on Mondays
  issues:
    types:
    - reopened
    - opened
  pull_request:
    types:
    - reopened
    - opened
jobs:
  notify:
    if: github.actor!= 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: need_triage
        with:
          route: GET /repos/FairwindsOps/${{ github.event.repository.name }}/issues?labels=triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Scheduled Reminders
        env:
          TITLES: ${{ join(fromJSON(steps.need_triage.outputs.data).*.title, ';') }}
          LINKS: ${{ join(fromJSON(steps.need_triage.outputs.data).*.html_url, ';') }}
        run: |
          echo "Scheduled reminder! ${TITLES}"
          IFS=';' read -r -a titles <<< "$TITLES"
          IFS=';' read -r -a links <<< "$LINKS"
          message=""
          for index in "${!links[@]}"; do
              title=${titles[$index]}
              link=${links[$index]} 
              echo "$index $title $link"
              message="$message- <$link|$title>\\n"
          done
          echo "message: $message"
          echo '{
            "text": "Needs Triage",
            "blocks": [
            	{
            		"type": "section",
            		"text": {
            			"type": "mrkdwn",
            			"text": "$message"
            		}
            	}
            ]
          }' > body-template.json
          export message=$(echo "${message}" | sed 's/"//g')
          envsubst < body-template.json > body.json
          cat body.json
          curl -X POST "${{ secrets.SLACK_INCOMING_WEBHOOK }}" -H "Content-type: application/json" -d @./body.json

      - name: Issue Notification
        if: github.event.issue.title != ''
        env:
          TITLE: "${{ github.event.issue.title }}"
          EVENT: github.event.pull_request.merged == true
          LINK: "https://github.com/FairwindsOps/${{ github.event.repository.name }}/pulls/${{ github.event.issue.number }}"
        run: |
          echo '{
            "text": "New Pull Request",
            "blocks": [
            	{
            		"type": "section",
            		"text": {
            			"type": "mrkdwn",
            			"text": ":issue: New Issue: <${LINK}|${TITLE}>"
            		}
            	}
            ]
          }' > body-template.json
          envsubst < body-template.json > body.json
          curl -X POST "${{ secrets.SLACK_INCOMING_WEBHOOK }}" -H "Content-type: application/json" -d @./body.json

      - name: PR Notification
        if: github.event.pull_request.title != ''
        env:
          TITLE: "${{ github.event.pull_request.title }}"
          LINK: "https://github.com/FairwindsOps/${{ github.event.repository.name }}/pulls/${{ github.event.pull_request.number }}"
        run: |
          echo '{
            "text": "New Pull Request",
            "blocks": [
            	{
            		"type": "section",
            		"text": {
            			"type": "mrkdwn",
            			"text": ":pr: New Pull Request: <${LINK}|${TITLE}>"
            		}
            	}
            ]
          }' > body-template.json
          envsubst < body-template.json > body.json
          curl -X POST "${{ secrets.SLACK_INCOMING_WEBHOOK }}" -H "Content-type: application/json" -d @./body.json
