name: Triage issues
on:
  schedule:
#   - cron: '0 16 * * Mon' # noon ET on Mondays
    - cron: '*/5 * * * *' # every 5 minutes (for testing)
  issues:
    types:
      - reopened
      - opened
  pull_request:
#    types:
#    - reopened
#    - opened
jobs:
  notify:
    if: github.actor!= 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Find open issues
        id: issues
        uses: lee-dohm/select-matching-issues@v1
        with:
          query: 'label:triage is:open'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Scheduled Reminders
        env:
          OPEN_ISSUES: "${{steps.bugs.outputs.path}}"
        run: |
          echo "Scheduled reminder! $OPEN_ISSUES"
          cat $OPEN_ISSUES
      - name: Issue Notification
        if: github.event.issue.title != ''
        env:
          TITLE: "${{ github.event.issue.title }}"
          EVENT: github.event.pull_request.merged == true
          LINK: "github.com/FairwindsOps/${{ github.event.repository.name }}/pulls/${{ github.event.issue.number }}"
        run: |
          echo '{
            "text": "New Pull Request",
            "blocks": [
            	{
            		"type": "section",
            		"text": {
            			"type": "mrkdwn",
            			"text": ":issue: New Issue: ${TITLE}"
            		}
            	},
            	{
            		"type": "section",
            		"text": {
            			"type": "mrkdwn",
            			"text": "${LINK}"
            		},
            	},
            ]
          }' > body-template.json
          envsubst < body-template.json > body.json
          curl -X POST "${{ secrets.SLACK_INCOMING_WEBHOOK }}" -H "Content-type: application/json" -d @./body.json

      - name: PR Notification
        if: github.event.pull_request.title != ''
        env:
          TITLE: "${{ github.event.pull_request.title }}"
          LINK: "github.com/FairwindsOps/${{ github.event.repository.name }}/pulls/${{ github.event.pull_request.number }}"
        run: |
          echo '{
            "text": "New Pull Request",
            "blocks": [
            	{
            		"type": "section",
            		"text": {
            			"type": "mrkdwn",
            			"text": ":pr: New Pull Request: ${TITLE}"
            		}
            	},
            	{
            		"type": "section",
            		"text": {
            			"type": "mrkdwn",
            			"text": "${LINK}"
            		},
            	},
            ]
          }' > body-template.json
          envsubst < body-template.json > body.json
          curl -X POST "${{ secrets.SLACK_INCOMING_WEBHOOK }}" -H "Content-type: application/json" -d @./body.json
